-- Seed data ported from the mockup (sw-youth-racing-site.jsx) for local/dev use.

insert into clubs (name, location, website, disciplines, age_note, kids_only, founded, summary) values
  ('Mid Devon CC', 'Newton Abbot, Devon', 'https://www.middevon.cc', array['road','xc','cx']::club_discipline[], 'Go-Ride youth section, ages 8–16', false, '1930', 'One of the South West''s largest and longest-established clubs. British Cycling Go-Ride registered, with junior coaching across road, mountain bike and cyclocross sitting alongside a full adult racing programme — including hosting the Dartmoor Classic sportive.'),
  ('Wheal Velocity', 'Truro, Cornwall', 'https://www.whealvelocity.com', array['road','xc','cx']::club_discipline[], 'Junior Academy, Saturdays 1.30–4pm', false, null, 'Based at Wheal Jane''s traffic-free circuits near Truro, and widely regarded as the largest youth cycling club in the South West. Runs a Junior Academy, Development Squad and Race Team alongside road and off-road sessions for all ages.'),
  ('Exeter Wheelers', 'Exeter, Devon', 'https://www.exeterwheelers.co.uk', array['road']::club_discipline[], 'Exeter Wheelers Academy, ages 8+', false, '1924', 'A road-focused club founded in 1924, with a relaunched Youth Academy and British Cycling Go-Ride Focus Club status. Runs time trials, criteriums and a full programme of social and training rides year-round.'),
  ('North Devon Velo', 'Barnstaple, Devon', 'https://www.northdevonvelo.com', array['road','xc','cx']::club_discipline[], 'Youth section Saturdays at Petroc, under 16s', false, null, 'The only British Cycling Go-Ride accredited club in North Devon, formed from a merger of North Devon Wheelers and Taw Velo. Covers road, time trial, track, cyclocross and mountain biking, and hosts an SWCX round at Coxleigh Barton.'),
  ('Dartmoor Velo', 'Tavistock, Devon', 'https://www.dartmoorvelo.co.uk', array['road','xc','cx']::club_discipline[], 'Ages 8–16 — youth only, no adult section', true, null, 'A dedicated youth club covering West Devon and North Cornwall, with Saturday morning coaching in road, mountain bike and cyclocross for young riders. There''s no separate adult racing programme — it''s built around junior riders.');

insert into events (title, discipline, status, start_datetime, all_day, venue_name, region, kids_only, age_categories, booking_status, booking_link, organiser_url, approved, source_type, published_via) values
  ('SWCX Round 1 — Torbay', 'cx', 'confirmed', '2026-09-13 09:00:00+01', true, 'Torbay', 'devon', false, array['u8','u10','u12','u14','u16']::age_category[], 'open', 'https://example.com/book', 'https://example.com', true, 'manual', 'auto'),
  ('SWCX Round 2 — Scorrier Estate', 'cx', 'confirmed', '2026-09-27 09:00:00+01', true, 'Scorrier Estate', 'cornwall', false, array['u8','u10','u12','u14','u16']::age_category[], 'open', 'https://example.com/book', 'https://example.com', true, 'manual', 'auto'),
  ('SWCX Round 3 — Saltash School', 'cx', 'confirmed', '2026-10-04 09:00:00+01', true, 'Saltash School', 'cornwall', false, array['u8','u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('SWCX Round 4 — Wadebridge', 'cx', 'confirmed', '2026-10-11 09:00:00+01', true, 'Wadebridge', 'cornwall', false, array['u8','u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('SWCX Round 5 — Newham Top', 'cx', 'confirmed', '2026-11-01 09:00:00+01', true, 'Newham Estate', 'devon', false, array['u8','u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('SWCX Round 6 — Escot', 'cx', 'confirmed', '2026-11-15 09:00:00+01', true, 'Escot', 'devon', false, array['u8','u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('SWCX Round 7 — Arlington', 'cx', 'confirmed', '2026-11-22 09:00:00+01', true, 'Arlington Court', 'devon', false, array['u8','u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('SWCX Round 8 — Exeter Bike Park', 'cx', 'confirmed', '2026-11-29 09:00:00+01', true, 'Exeter Bike Park', 'devon', false, array['u8','u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('SWCX Round 9 — Newham Bottom', 'cx', 'confirmed', '2026-12-06 09:00:00+01', true, 'Newham Estate', 'devon', false, array['u8','u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('SWCX Round 10 — Perranporth', 'cx', 'confirmed', '2026-12-13 09:00:00+01', true, 'Perranporth', 'cornwall', false, array['u8','u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('Haldon Forest Youth XC — Rd 1', 'xc', 'confirmed', '2026-08-16 09:00:00+01', true, 'Haldon Forest', 'devon', true, array['u10','u12','u14','u16']::age_category[], 'open', 'https://example.com/book', 'https://example.com', true, 'manual', 'auto'),
  ('Haldon Forest Youth XC — Rd 2', 'xc', 'provisional', '2026-09-20 09:00:00+01', true, 'Haldon Forest', 'devon', true, array['u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('Haldon Forest Youth XC — Rd 3', 'xc', 'confirmed', '2026-10-18 09:00:00+01', true, 'Haldon Forest', 'devon', true, array['u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('Devon Youth Road Race Series — Rd 1', 'road', 'confirmed', '2026-08-23 09:00:00+01', true, 'Simpson Cross, Crediton', 'devon', true, array['u12','u14','u16']::age_category[], 'open', 'https://example.com/book', 'https://example.com', true, 'manual', 'auto'),
  ('Cornwall CC Junior Road Race', 'road', 'confirmed', '2026-09-06 09:00:00+01', true, 'Wadebridge', 'cornwall', false, array['u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('MDCC Youth Time Trial Taster', 'road', 'confirmed', '2026-10-25 09:00:00+01', true, 'A38 Course, Plymouth', 'devon', true, array['u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('Exmouth Sprint Triathlon — Junior Wave', 'tri', 'confirmed', '2026-08-30 09:00:00+01', true, 'Exmouth Seafront', 'devon', false, array['u12','u14','u16']::age_category[], 'open', 'https://example.com/book', 'https://example.com', true, 'manual', 'auto'),
  ('Truro Junior Aquathlon', 'tri', 'confirmed', '2026-09-14 09:00:00+01', true, 'Boconnoc Estate', 'cornwall', true, array['u10','u12','u14']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('MDCC Youth Academy — Tuesday Track', 'clusters', 'confirmed', '2026-08-18 09:00:00+01', true, 'Tiverton Track', 'devon', true, array['u8','u10','u12','u14','u16']::age_category[], 'open', 'https://example.com/book', 'https://example.com', true, 'manual', 'auto'),
  ('Exeter Wheelers Youth — Thursday Skills', 'clusters', 'confirmed', '2026-08-20 09:00:00+01', true, 'Haldon Forest', 'devon', true, array['u8','u10','u12']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('Bowman Go-Ride Skills Day', 'clusters', 'confirmed', '2026-08-29 09:00:00+01', true, 'Newton Abbot Leisure Centre', 'devon', true, array['u8','u10']::age_category[], 'open', 'https://example.com/book', 'https://example.com', true, 'manual', 'auto'),
  ('Cornwall Go-Ride Taster Session', 'clusters', 'provisional', '2026-09-12 09:00:00+01', true, 'Par Track', 'cornwall', true, array['u8']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('MDCC Youth Academy — Tuesday Track', 'clusters', 'confirmed', '2026-08-25 09:00:00+01', true, 'Tiverton Track', 'devon', true, array['u8','u10','u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto'),
  ('SW Youth Duathlon', 'tri', 'confirmed', '2026-10-11 09:00:00+01', true, 'Bude', 'cornwall', false, array['u12','u14','u16']::age_category[], 'planned', null, 'https://example.com', true, 'manual', 'auto');

