#!/bin/bash
# Appends a weekly Vercel Web Analytics summary to docs/traffic-reports.md.
# Run manually with `npm run traffic-report`, or via the launchd job set up
# by scripts/install-traffic-report-schedule.sh (Sunday evenings).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_FILE="$REPO_DIR/docs/traffic-reports.md"
PROJECT="sw-calendar"
# launchd runs with a minimal PATH — make sure it can find `vercel` (installed
# globally under nvm's node bin) and `jq`/homebrew tools. Update the nvm path
# below if you switch node versions.
PATH="/opt/homebrew/bin:/Users/steve/.nvm/versions/node/v22.23.2/bin:$PATH"

cd "$REPO_DIR"

pageviews_json=$(vercel metrics vercel.analytics_pageview.count --since 7d --project "$PROJECT" --prod --json)
visitors_json=$(vercel metrics vercel.analytics_pageview.count --aggregation unique/visitor_id --since 7d --project "$PROJECT" --prod --json)
top_pages_json=$(vercel metrics vercel.analytics_pageview.count --group-by request_path --since 7d --limit 5 --project "$PROJECT" --prod --json)
top_referrers_json=$(vercel metrics vercel.analytics_pageview.count --group-by referrer_hostname --since 7d --limit 5 --project "$PROJECT" --prod --json)

pageviews=$(echo "$pageviews_json" | jq -r '.summary[0].vercel_analytics_pageview_count_sum // 0')
visitors=$(echo "$visitors_json" | jq -r '.summary[0].vercel_analytics_pageview_count_unique_visitor_id // 0')

top_pages=$(echo "$top_pages_json" | jq -r '.summary[] | "- `\(.request_path)` — \(.vercel_analytics_pageview_count_sum)"')
top_referrers=$(echo "$top_referrers_json" | jq -r '.summary[] | "- \(if .referrer_hostname == null or .referrer_hostname == "" then "(direct / no referrer)" else .referrer_hostname end) — \(.vercel_analytics_pageview_count_sum)"')
[ -z "$top_referrers" ] && top_referrers="- (no traffic this week)"

week_end=$(date +"%Y-%m-%d")
week_start=$(date -v-7d +"%Y-%m-%d" 2>/dev/null || date -d "7 days ago" +"%Y-%m-%d")

if [ ! -f "$REPORT_FILE" ]; then
  echo "# Weekly traffic reports" > "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  echo "Generated by [scripts/weekly-traffic-report.sh](../scripts/weekly-traffic-report.sh) from Vercel Web Analytics." >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
fi

{
  echo "## Week of $week_start to $week_end"
  echo ""
  echo "- Page views: $pageviews"
  echo "- Unique visitors: $visitors"
  echo ""
  echo "**Top pages:**"
  echo "$top_pages"
  echo ""
  echo "**Top referrers:**"
  echo "$top_referrers"
  echo ""
} >> "$REPORT_FILE"

echo "Traffic report appended to $REPORT_FILE"
